version: '3.9'

services:
  dialoqbase:
    image: n4z3m/dialoqbase:latest
    container_name: dialoqbase
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@dialoqbase-pg:5432/dialoqbase
      DB_REDIS_URL: redis://redis:6379
    env_file:
      - imp.env
    depends_on:
      - dialoqbase-pg
      - redis
    volumes:
      - .uploads:/app/uploads

  dialoqbase-pg:
    image: n4z3m/dialoqbase-pg:latest
    container_name: dialoqbase-postgres
    restart: unless-stopped
    volumes:
      - .postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - .redis:/data